### ISSUE TITLE
When I use redis as storage, but the quota key have no expire time?

### ISSUE THREAD

**Issue by chainren** [marcosbarbero/spring-cloud-zuul-ratelimit#131]
Hi, Marcos, I use redis, the config like this :
```
policy-list:
      zuullimit:
        - limit: 10 
          quota: 1000 
          refresh-interval: 60 
          type: 
            - url
```

I found the redis key for quota was always not expired, the key 'req-limit:zuullimit:/foo-quota' ttl is -1.
When the request sum time is large than quota*1000(mills)，all of the subsequent request was refused.
I thought it's not right, the quota maped the redis key also need a expire time.
I thought this code in RedisRateLimiter class, have a little question,
``` 
// Redis returns 1 when the key is incremented for the first time, and the expiration time is set
            if (current != null && current.equals(1L)) {
                handleExpiration(key, refreshInterval);
            }
```
When the RateLimitPostFilter run method called, the requestTime must large than 0, so the key 'req-limit:zuullimit:/foo-quota' first set and incr return result not be the 1， and the handleExpiration method can't be called.

So, please help me what can i do? thanks for you help!
