### ISSUE TITLE
what's wrong with it???

### ISSUE THREAD

**Issue by celesky** [marcosbarbero/spring-cloud-zuul-ratelimit#156]
springboot 2.1.4.RELEASE

```
zuul:
  routes:
    commons-service:
      path: /commons-service/**
      serviceId: commons-service

  ratelimit:
    key-prefix: 'ZUUL_RATELIMIT'
    enabled: true
    repository: REDIS
    behind-proxy: true
    add-response-headers: true
    default-policy-list: #optional - will apply unless specific policy exists
      - limit: 10 #optional - request number limit per refresh interval window
        quota: 1000 #optional - request time limit per refresh interval window (in seconds)
        refresh-interval: 60 #default value (in seconds)
      - type: #optional
          - url
    policyList:
      commons-service:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - url
        - type: #optional value for each type
            - url=/commons-service #url prefix

```

***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'zuul.ratelimit' to com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.properties.RateLimitProperties failed:

    Property: zuul.ratelimit.defaultPolicyList
    Value: [RateLimitProperties.Policy(refreshInterval=60, limit=10, quota=1000, type=[]), RateLimitProperties.Policy(refreshInterval=60, limit=null, quota=null, type=[RateLimitProperties.Policy.MatchType(type=URL, matcher=null)])]
    Reason: Policy must contain limit, quota or both

    Property: zuul.ratelimit.policyList
    Value: {commons-service=[RateLimitProperties.Policy(refreshInterval=60, limit=10, quota=1000, type=[RateLimitProperties.Policy.MatchType(type=URL, matcher=null)]), RateLimitProperties.Policy(refreshInterval=60, limit=null, quota=null, type=[RateLimitProperties.Policy.MatchType(type=URL, matcher=/commons-service)])]}
    Reason: Policy must contain limit, quota or both

Action:

Update your application's configuration

**Comment by lchayoun** [comment]
Hi @celesky 
Your second policy for common-service (with the specific url) does not contain limit / quota.

**Comment by celesky** [comment]
@lchayoun thanks for your reply, could you tell me how to config it ? i'm confused

**Comment by lchayoun** [comment]
this policy (last thing in your configuration - second item under `zuul.ratelimit.policyList.commons-service`):

```
        - type: #optional value for each type
            - url=/commons-service #url prefix
```

doesn't have `limit` or `quota`.

**Comment by celesky** [comment]
@lchayoun 
so it should config like this?  but it also not work.
```
zuul:
  routes:
    commons-service:
      path: /commons-service/**
      serviceId: commons-service

  ratelimit:
    key-prefix: 'ZUUL_RATELIMIT'
    enabled: true
    repository: REDIS
    behind-proxy: true
    add-response-headers: true
    default-policy-list: #optional - will apply unless specific policy exists
      - limit: 10 #optional - request number limit per refresh interval window
        quota: 1000 #optional - request time limit per refresh interval window (in seconds)
        refresh-interval: 60 #default value (in seconds)
      - type: #optional
          - url
    policy-list:
      commons-service:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - url
        - type: #optional value for each type
            - url=/commons-service #url prefix
            - limit: 10 #optional - request number limit per refresh interval window
            - quota: 1000 #optional - request time limit per refresh interval window (in seconds)

```


this is the professinal sample ,actually i just copied it 😢 
```
zuul:
  ratelimit:
    key-prefix: your-prefix
    enabled: true
    repository: REDIS
    behind-proxy: true
    add-response-headers: true
    default-policy-list: #optional - will apply unless specific policy exists
      - limit: 10 #optional - request number limit per refresh interval window
        quota: 1000 #optional - request time limit per refresh interval window (in seconds)
        refresh-interval: 60 #default value (in seconds)
        type: #optional
          - user
          - origin
          - url
          - httpmethod
    policy-list:
      myServiceId:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - user
            - origin
            - url
        - type: #optional value for each type
            - user=anonymous
            - origin=somemachine.com
            - url=/api #url prefix
            - role=user
            - httpmethod=get #case insensitive
```

**Comment by lchayoun** [comment]
try:

```
zuul:
  routes:
    commons-service:
      path: /commons-service/**
      serviceId: commons-service

  ratelimit:
    key-prefix: 'ZUUL_RATELIMIT'
    enabled: true
    repository: REDIS
    behind-proxy: true
    add-response-headers: true
    default-policy-list: #optional - will apply unless specific policy exists
      - limit: 10 #optional - request number limit per refresh interval window
        quota: 1000 #optional - request time limit per refresh interval window (in seconds)
        refresh-interval: 60 #default value (in seconds)
      - type: #optional
          - url
    policy-list:
      commons-service:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - url
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          type: #optional
            - url
```
