### ISSUE TITLE
use "repository: redis"  for help

### ISSUE THREAD

**Issue by fanling521** [marcosbarbero/spring-cloud-zuul-ratelimit#184]
hi,I have a question, if you have time, please give me some opinions, thank you.
version:2.2.4.RELEASE
springboot version:2.1.6.RELEASE
spring cloud version:Greenwich.RELEASE
**error:**
```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'stringRedisTemplate' available
APPLICATION FAILED TO START
***************************

Description:

A component required a bean named 'stringRedisTemplate' that could not be found.


Action:

Consider defining a bean named 'stringRedisTemplate' in your configuration.
```

**yml**

```yml
ratelimit:
    key-prefix: spring-cloud-open       
    enabled: true
    repository: redis
    behind-proxy: true                 
    add-response-headers: true
    default-policy-list:
      - limit: 3
        quota: 2
        refresh-interval: 15 
```

**pom**

```xml
        <!-- redis -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <!-- ratelimit -->
        <dependency>
            <groupId>com.marcosbarbero.cloud</groupId>
            <artifactId>spring-cloud-zuul-ratelimit</artifactId>
        </dependency>
```
