### ISSUE TITLE
"add-response-headers" property does not seem to be working

### ISSUE THREAD

**Issue by devc0n** [marcosbarbero/spring-cloud-zuul-ratelimit#188]
The ratelimit headers do get added to the response by default, but when i try to remove them using the "add-response-headers" property they are still in the response. 

> If you are using Spring Boot version 1.5.x you MUST use Spring Cloud Zuul RateLimit version 1.7.x. 

I picked up on this, so i am using ratelimit version 1.7.3.RELEASE

my current config looks like this.

```
ratelimit:
    enabled: true
    add-response-headers: false
    repository: JPA
    policy-list:
      service-x:
        - limit: 60
          refresh-interval: 10

```
