### ISSUE TITLE
How to filter by Authenticated User?

### ISSUE THREAD

**Issue by shenlihartono** [marcosbarbero/spring-cloud-zuul-ratelimit#341]
Spring boot 2.1.4.RELEASE
rate limit version 2.4.0.RELEASE

Hi guys, I tried to implement the usage for filter by user but i got error

```
  ratelimit:
    enabled: true
    key-prefix: 'ZUUL_RATELIMIT'
    repository: REDIS
    behind-proxy: true
    default-policy-list:
      - limit: 3
        quota: 1000
        refresh-interval: 60
        type:
          - user
    policy-list:
      account-service:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - user
        - type:
            - user=anonymous
```
I followed the sample YAML config from here: https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit#usage

but I got this error after running my zuul gateway
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'zuul.ratelimit' to com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.properties.RateLimitProperties failed:

    Property: zuul.ratelimit.policyList
    Value: {account-service=[com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.properties.RateLimitProperties$Policy@3509f32d, com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.properties.RateLimitProperties$Policy@56adb75e]}
    Reason: Policy must contain limit, quota or both


Action:

Update your application's configuration
```

By the way, my ultimate goal is to filter by any authenticated user, can it be done? what value should I set to `user=xxxxx`

is the opposite of `user=anonymous` => `user=authenticated`?

I really need to sample yaml for filtering authenticated user, but cannot find any after googling around.

Thanks guys.

**Comment by lchayoun** [comment]
Hi @shenlihartono 

Basically, type user without a value is any user
with a value, will be only for the specific user
But each one need to have all the parameters

Try this one:
```
  ratelimit:
    enabled: true
    key-prefix: 'ZUUL_RATELIMIT'
    repository: REDIS
    behind-proxy: true
    default-policy-list:
      - limit: 3
        quota: 1000
        refresh-interval: 60
        type:
          - user
    policy-list:
      account-service:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type:
            - user
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type:
            - user=anonymous
```

**Comment by shenlihartono** [comment]
Hi @lchayoun 

> Try this one:
> 
> ```
>   ratelimit:
>     enabled: true
>     key-prefix: 'ZUUL_RATELIMIT'
>     repository: REDIS
>     behind-proxy: true
>     default-policy-list:
>       - limit: 3
>         quota: 1000
>         refresh-interval: 60
>         type:
>           - user
>     policy-list:
>       account-service:
>         - limit: 10 #optional - request number limit per refresh interval window
>           quota: 1000 #optional - request time limit per refresh interval window (in seconds)
>           refresh-interval: 60 #default value (in seconds)
>           type:
>             - user
>         - limit: 10 #optional - request number limit per refresh interval window
>           quota: 1000 #optional - request time limit per refresh interval window (in seconds)
>           refresh-interval: 60 #default value (in seconds)
>           type:
>             - user=anonymous
> ```

This works. The result is something like this when I hit it using Postman
![image](https://user-images.githubusercontent.com/19544482/82401315-abaf3100-9a83-11ea-8d16-a6b352a34b6b.png)

Although not what I expected but I guess it's fine since I have no intention to filter out anonymous user, because without bearer token the client cannot access the protected resources.

> Basically, type user without a value is any user
> with a value, will be only for the specific user
> But each one need to have all the parameters
> 

This is what I'm curious about, and would like to confirm since yesterday.

So when I typed in 
```
...
type:
   - user
...
```

that basically means filter out any user, whether it's anonymous or authenticated user right?

When you say I must put value for specific user, does that mean config like this:
```
    policy-list:
      account-service:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type:
            - user=user01
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type:
            - user=user02
...
and so on..
```

Can I have a common config which only applied to / affected to all the authenticated users?

So, when I have let say 100 users, I have to make the 100 policy-list for account-service then?

What I'm looking for is to make one common policy-list which will affect each authenticated user in the same way (any users which access using bearer token) let say to only have limit 3-5 times on every 1 minute

Can it be achieved like this?

**Comment by lchayoun** [comment]
`that basically means filter out any user, whether it's anonymous or authenticated user right?`
yes

`Can I have a common config which only applied to / affected to all the authenticated users?`
You can use the type `role` instead of user and in the role specify `USER` which only authenticated users has.

`So, when I have let say 100 users, I have to make the 100 policy-list for account-service then?`
No, you can user the `user` without the value, so it will be applied to all users

`Can it be achieved like this?`
You can achieve (example here is 3 requests per minute for each user) using:
```
    default-policy-list:
      - limit: 3
        refresh-interval: 60
        type:
          - user
```
