### ISSUE TITLE
Unable to match serviceId and routeId

### ISSUE THREAD

**Issue by ZoraZora59** [marcosbarbero/spring-cloud-zuul-ratelimit#389]
rateLimit version 2.4.1 
Here is my yml configuration.
```
ratelimit:
    key-prefix: ${spring.cloud.client.ip-address}:apiserv_rate_limit
    enabled: true
    repository: REDIS
    behind-proxy: true
    default-policy-list: #optional - will apply unless specific policy exists
      - limit: 10 
        quota: 1000 
        refresh-interval: 2000 
        type: 
          - url
    policy-list:
      cloud-currencyBackend:
        - limit: 10
          quota: 1000
          refresh-interval: 60
          type: #optional
            - url=/backend/currency/**
routes:
    cloud-currencyBackend:
      path: /backend/currency/**
      serviceId: currency-service
      stripPrefix: false
```

Every time while `RateLimitProperties.getPolicies(key)` execute , the `key` will be `routeId` likes `/backend/currency/**`.
My `policyList` is `serviceId : targetPolicy` likes `cloud-currencyBackend: some policy`. Therefore the result of this method will always be `defaultPolicyList`.

How can I make this work ?

**Comment by ZoraZora59** [comment]
<dependency>
    <groupId>com.marcosbarbero.cloud</groupId>
    <artifactId>spring-cloud-zuul-ratelimit</artifactId>
    <version>2.4.1.RELEASE</version>
</dependency>

**Comment by ZoraZora59** [comment]
```
<dependency>
    <groupId>com.marcosbarbero.cloud</groupId>
    <artifactId>spring-cloud-zuul-ratelimit</artifactId>
    <version>2.4.1.RELEASE</version>
</dependency>
```

**Comment by ZoraZora59** [comment]
Hi @lchayoun , could you please offer me some help?

**Comment by ZoraZora59** [comment]
Please @marcosbarbero .  I wanne commit a fix branch for this issue if no available solution for it,.

**Comment by lchayoun** [comment]
is `cloud-currencyBackend` the name of the service that is service the `/backend/currency/**` endpoints?

**Comment by ZoraZora59** [comment]
> is `cloud-currencyBackend` the name of the service that is serving the `/backend/currency/**` endpoints?

I tried “currency-service” but it doesn’t work as well.

**Comment by marcosbarbero** [comment]
@ZoraZora59 thanks for the feedback, but I'm a little confused, what's the service name? Does the request work without the rate-limiting?

**Comment by ZoraZora59** [comment]
> @ZoraZora59 thanks for the feedback, but I'm a little confused, what's the service name? Does the request work without the rate-limiting?

The application name of my service is "currency-service". It marked as "cloud-currencyBackend" in "zuul.routes".

**Comment by ZoraZora59** [comment]
I found a method named  `policy` at  calss `AbstractRateLimitFilter`.
```
    protected List<Policy> policy(Route route, HttpServletRequest request) {
        String routeId = Optional.ofNullable(route).map(Route::getId).orElse(null);
        return properties.getPolicies(routeId).stream()
            .filter(policy -> applyPolicy(request, route, policy))
            .collect(Collectors.toList());
    }
```

I guess it might should be 
```
    protected List<Policy> policy(Route route, HttpServletRequest request) {
        String routeId = Optional.ofNullable(route).map(Route::getLocation).orElse(null);
        return properties.getPolicies(routeId).stream()
            .filter(policy -> applyPolicy(request, route, policy))
            .collect(Collectors.toList());
    }
```

Notice the second row , `Route::getId` replaced into `Route::getLocation`.

**Comment by ZoraZora59** [comment]
> @ZoraZora59 thanks for the feedback, but I'm a little confused, what's the service name? Does the request work without the rate-limiting?

The request of test is "curl localhost:8080/backend/currency/sleep100ms".

**Comment by marcosbarbero** [comment]
Can you share a project reproducing the problem?
Also, I noticed you have it configured like this: 

```
- url=/backend/currency/**
```

If you want to use URL patterns you should do it like this:

```
- url_pattern=/backend/currency/*
```

**Comment by ZoraZora59** [comment]
> Can you share a project reproducing the problem?
> Also, I noticed you have it configured like this:
> 
> ```
> - url=/backend/currency/**
> ```
> 
> If you want to use URL patterns you should do it like this:
> 
> ```
> - url_pattern=/backend/currency/*
> ```

I switch to version 2.0.6.RELEASE , and set yml as follow:
```
  ratelimit:
    key-prefix: ${spring.cloud.client.ip-address}:apiserv_rate_limit
    enabled: true
    repository: REDIS
    behind-proxy: true
    default-policy-list: #optional - will apply unless specific policy exists
      - limit: 10 #可选 - 每个刷新时间窗口对应的请求数量限制
        quota: 1000 #可选-  每个刷新时间窗口对应的请求时间限制（秒）
        refresh-interval: 2000 # 刷新时间窗口的时间，默认值 (秒)
        type: #可选 限流方式
          - url
    policy-list:
      currency-service:
        - limit: 5 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - type: URL
              matcher: /backend/currency/
```
After I update source code and install in my local mvn repository, it worked.

**Comment by ZoraZora59** [comment]
> Can you share a project reproducing the problem?
> Also, I noticed you have it configured like this:
> 
> ```
> - url=/backend/currency/**
> ```
> 
> If you want to use URL patterns you should do it like this:
> 
> ```
> - url_pattern=/backend/currency/*
> ```

To reproducing the problem , here is part of my project config.

My own service yml as follow :
```
server:
  port: 2333
spring:
  application:
    name: currency-service
```
Configured in api-zuul as follow : 
```
server:
  port: 8080
spring:
  application:
    name: api-zuul
zuul:
  ratelimit:
    key-prefix: ${spring.cloud.client.ip-address}:apiserv_rate_limit
    enabled: true
    repository: REDIS
    behind-proxy: true
    default-policy-list: 
      - limit: 10
        quota: 1000 
        refresh-interval: 2000 
        type:
          - url
    policy-list:
      currency-service:
        - limit: 5
          quota: 1000
          refresh-interval: 60 
          type:
            - type: URL
              matcher: /backend/currency/
  routes:
    cloud-currencyBackend:
      path: /backend/currency/**
      serviceId: currency-service
      stripPrefix: false
```
