### ISSUE TITLE
 Limiting rate (Downstream) services.

### ISSUE THREAD

**Issue by Gondagar** [marcosbarbero/spring-cloud-zuul-ratelimit#435]
Hi, what about downstream service?
How can i configure yml file? 

My current yml file  ---------------------------------------------------------

```
zuul:
  prefix: /api
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
    foo-service:
      path: /foo/**
      serviceId: foo-service
  ratelimit:
    behind-proxy: true
    response-headers: standard
    enabled: true
    repository: REDIS
    policy-list:
      auth-service:     -------------------------   it is good?
        - limit: 4
          refresh-interval: 15
          type:
            - origin
  strip-prefix: false   -------------------------  it is good?

```

 ----------------------------------------------------------------- end
 
  
  Pleace help me with this config file :)
