### ISSUE TITLE
Request.getRemoteUser () is always null.

### ISSUE THREAD

**Issue by immno** [marcosbarbero/spring-cloud-zuul-ratelimit#52]
I use eureka, zuul and oauth (spring-cloud-starter-oauth2), request.getRemoteUser () is always null.
`In DefaultRateLimitKeyGenerator`:
```
if (types.contains(Type.USER)) {
    joiner.add(request.getRemoteUser() != null ? request.getRemoteUser() : ANONYMOUS_USER);
}
```
I miss some something?

**Comment by lchayoun** [comment]
is the endpoint authenticated? in other endpoints are you able to retrieve the user?

**Comment by immno** [comment]
User information is obtained through the token(`/user`).

**Comment by lchayoun** [comment]
can you create a repository that reproduce the issue?
I'm finding it hard to understand the issue.

When running with spring security the remote user is being set on the request on all authenticated endpoints.

**Comment by immno** [comment]
I can hardly describe this problem.
I use spring cloud related components to build such as  `eureka`,`zuul `,`spring cloud oauth2.0`;
in `zuul`:
```
  routes:
    auth-server:
      path: /uaa/**
      serviceId: oauth2
      sensitiveHeaders:
  ratelimit:
    enabled: true
    repository: IN_MEMORY
    behind-proxy: true
    policy-list:
      auth-server:
        - limit: 10
          quota: 1000
          refresh-interval: 60
          type:
            - user
            - origin
            - url
```
in `oauth 2.0`:
```
@GetMapping("/user")
    public Principal user(Principal user) {
        return user;
    }
```
my request:
![image](https://user-images.githubusercontent.com/10646884/35546921-2fe49588-05b1-11e8-96f9-c422d617913c.png)

debug result is:
![image](https://user-images.githubusercontent.com/10646884/35546996-8b37200e-05b1-11e8-96b3-c700ece341f6.png)
