### ISSUE TITLE
failed to run zuul-ratelimit

### ISSUE THREAD

**Issue by oldbeee** [marcosbarbero/spring-cloud-zuul-ratelimit#84]
I add the depency 

```xml
<dependency>
            <groupId>com.marcosbarbero.cloud</groupId>
            <artifactId>spring-cloud-zuul-ratelimit</artifactId>
            <version>1.7.2.RELEASE</version>
        </dependency>
```
and the yml is :
```yaml
zuul:
  routes:
    mercury-service:
      path: /ark/open_api/**
      url:  http://mercury-default-upd-product.dev.xiaohongshu.com/
      stripPrefix: false
  ratelimit:
    enable: true
    behind-proxy: true
#    repository: JPA
    policies:
      mercury-service:
        limit: 2
        quota: 1
        refresh-interval: 30
        type:
          - URL
          - ORIGIN
          - USER
```
then I run the springboot application, but when I call the API,the policies is not used ,should I over write a filter extends RateLimitPreFilter.
