### ISSUE TITLE
Does not work for a specific url or user

### ISSUE THREAD

**Issue by pggsnap** [marcosbarbero/spring-cloud-zuul-ratelimit#95]
myServiceId:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
        - type: #optional value for each type
            - user=anonymous
            - origin=somemachine.com
            - url=/api #url prefix

application.yml as above.

for a specific user(anonymous) and url(/api)，the key generated is ${spring.application.name}:myServiceId，missing  url and user information.

That means  other users accessing the interface are also restricted.

**Comment by pggsnap** [comment]
@lchayoun  spring-cloud-zuul-ratelimit  2.0.2.RELEASE

```
zuul:
  routes:
    api-dw:
      path: /dw-service/**
      serviceId: dw-service
      stripPrefix: false
  ratelimit:
    enabled: true
    repository: redis
    behind-proxy: true
    pre-filter-order: 10
    policy-list:
      api-dw:
        - limit: 3
          refresh-interval: 10
        - type:
            - url=/dw-service/jres/test
            - user=test   # I want to limit the speed of the user test only.
```

curl -i -H "Authorization: Bearer 100a4946-811c-4778-8474-c6261669607e" http://localhost:8080/dw-service/jres/test      // username is test

I expect the generated key to be "gateway:api-dw:/dw-service/jres/test:test", But in fact the key is "gateway:api-dw"。

The response is:
```
everseeker@mbp ~$curl -i -H "Authorization: Bearer 100a4946-811c-4778-8474-c6261669607e" http://localhost:8080/dw-service/jres/test
HTTP/1.1 200
X-Application-Context: gateway:test:8080
X-RateLimit-Limit-gateway_api-dw: 3
X-RateLimit-Remaining-gateway_api-dw: 2
X-RateLimit-Reset-gateway_api-dw: -2000
Date: Thu, 19 Jul 2018 01:13:07 GMT
Content-Type: text/plain;charset=UTF-8
Transfer-Encoding: chunked
```

If I use other user(username is admin), the result is:
```
everseeker@mbp ~$curl -i -H "Authorization: Bearer d5fc54c1-8ad7-41f3-b682-d1ae88e45982" http://localhost:8080/dw-service/jres/test
HTTP/1.1 200
X-Application-Context: gateway:test:8080
X-RateLimit-Limit-gateway_api-dw: 3
X-RateLimit-Remaining-gateway_api-dw: 2
X-RateLimit-Reset-gateway_api-dw: -2000
Date: Thu, 19 Jul 2018 01:22:23 GMT
Content-Type: text/plain;charset=UTF-8
Transfer-Encoding: chunked
```
The user "admin" has also been limited, which is not what I expected.
